### ISSUE TITLE
Pre-Alpha Test

### ISSUE THREAD

**Issue by enzyme69** [hsab/Unified-Model-of-Organic-Growth#1]
Dear UMOG developers, although it is still pre-alpha, I am very curious about this add-on and really want to test every nodes. 

![livenoding615_umog_prealpha_sverchok_thumb2](https://user-images.githubusercontent.com/3952687/27982019-0a528514-63db-11e7-8a98-1360dd6fef42.png)

So far, the displacement seems to work. I am recording my experience with this add-on.  
https://youtu.be/Mi4Na_MsULQ

Wondering if I am using it correctly? And also in term of being able to "sculpt" procedurally, I am wondering how it works?

Do you have some kind of beta tester group or mailing list? I would like to join. Thanks!

**Comment by mp4** [comment]
Yes in general it appears you are using it correctly. The displace node you used does use the displace modifier. The sculpt nodes use the sculpt operator. The BMesh nodes displace the vertices of the mesh as if the texture is interpreted as a one dimensional array. Our texture node samples image(s) to the TextureResolution in our side panel before they are used by our nodes. we plan on adding more nodes and sockets over time. The sculpt nodes can be used on their own, their main purpose was to show the promise of the plugin. The sculpt nodes currently can be used without connections. All of the operators should work on 3d geometry.

The total number of times the node network will be executed is (EndFrame - StartFrame) * SubFrames. If this is zero or negative the network will not be executed.

There is currently a display bug with our texture node. The texture last selected is the one that is used internally by the plugin.

The texture alternator node should switch texture every subframe. If you can reproduce the issue you had on video in a clean blend file can you open a new issue and attach the blend file and I will take a look at it. You will need to zip it before github will allow you to attach it to an issue.

We don't currently have a beta tester group/mailing list I will let you know if/when we create one.

**Comment by enzyme69** [comment]
Thanks for this explanation, I will investigate this add-on further. Looking forward to Beta version!
